# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/noahj/Documents/GitHub/WavGenA/WavGenA.srcs/sources_1/bd/Top_Level_view/ip/Top_Level_view_axi_gpio_0_0/Top_Level_view_axi_gpio_0_0.xci
# IP: The module: 'Top_Level_view_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/noahj/Documents/GitHub/WavGenA/WavGenA.srcs/sources_1/bd/Top_Level_view/ip/Top_Level_view_axi_gpio_0_0/Top_Level_view_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_Level_view_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/noahj/Documents/GitHub/WavGenA/WavGenA.srcs/sources_1/bd/Top_Level_view/ip/Top_Level_view_axi_gpio_0_0/Top_Level_view_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_Level_view_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/noahj/Documents/GitHub/WavGenA/WavGenA.srcs/sources_1/bd/Top_Level_view/ip/Top_Level_view_axi_gpio_0_0/Top_Level_view_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_Level_view_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/noahj/Documents/GitHub/WavGenA/WavGenA.srcs/sources_1/bd/Top_Level_view/ip/Top_Level_view_axi_gpio_0_0/Top_Level_view_axi_gpio_0_0.xci
# IP: The module: 'Top_Level_view_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/noahj/Documents/GitHub/WavGenA/WavGenA.srcs/sources_1/bd/Top_Level_view/ip/Top_Level_view_axi_gpio_0_0/Top_Level_view_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_Level_view_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/noahj/Documents/GitHub/WavGenA/WavGenA.srcs/sources_1/bd/Top_Level_view/ip/Top_Level_view_axi_gpio_0_0/Top_Level_view_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_Level_view_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/noahj/Documents/GitHub/WavGenA/WavGenA.srcs/sources_1/bd/Top_Level_view/ip/Top_Level_view_axi_gpio_0_0/Top_Level_view_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_Level_view_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
